### ISSUE TITLE
博客页面有些资源不稳定

### ISSUE THREAD

**Issue by baiyutang** [huanz/blog#1]
![2019-01-29 11-55-22](https://user-images.githubusercontent.com/10782183/51883190-dc65e580-23bc-11e9-97ac-8830d3fbe0e8.png)

链接：https://www.noonme.com/about/

**Comment by baiyutang** [comment]
找不到 github-profile-summary.com 的服务器 IP 地址。
用站长工具，看到好多地方请求这个也是超时的

**Comment by huanz** [comment]
这个其实直接链接的一个别人的github的项目，应该是不可用了，等下我看看

**Comment by huanz** [comment]
@baiyutang 感谢提醒，已经修改了~~~~
